#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'game_shader_dx7'

def options(opt):
	# stub
	return

def configure(conf):
	conf.env.append_unique('DEFINES',[
		'FAST_MATERIALVAR_ACCESS',
		'STDSHADER_DX9_DLL_EXPORT',
		'GAME_SHADER_DLL',
		'SHADER_EDITOR_DLL_2013',
	])

def build(bld):
	source = [
		'BaseVSShader.cpp',
		'blur.cpp',
		'debug_lightingctrl.cpp',
		'debug_radiosity_grid.cpp',
		'debug_shadow.cpp',
		'deferred_brush.cpp',
		'deferred_decalModulate.cpp',
		'deferred_model.cpp',
		'deferred_utility.cpp',
		'defpass_composite.cpp',
		'defpass_gbuffer.cpp',
		'defpass_shadow.cpp',
		'IDeferredExt.cpp',
		'lighting_global.cpp',
		'lighting_pass_basic.cpp',
		'lighting_pass_volum.cpp',
		'lighting_volume.cpp',
		'lighting_world.cpp',
		'radiosity_blend.cpp',
		'radiosity_global.cpp',
		'radiosity_propagate.cpp',
		'screenspace_combine.cpp',
		'screenspace_shading.cpp',
		'volume_blend.cpp',
		'volume_prepass.cpp',
	]

	includes = [
		'.',
		'..',
		'../../game/client/shadereditor',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'fxctmp9',
		'vshtmp9'
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = ['tier0','shaderlib','tier1','mathlib', 'vstdlib']

	if bld.env.DEST_OS == 'android':
		libs += ['ANDROID_SUPPORT']

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android':
		#idk hack
		install_path += '/overcharged/bin'

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

