#ifndef WEAPONSTYPE_H
#define WEAPONSTYPE_H
#ifdef _WIN32
#pragma once
#endif
typedef enum
{
	TYPE_NONE = 0,
	TYPE_MELEE,
	TYPE_PISTOL,
	TYPE_DUAL_PISTOLS,
	TYPE_DUAL_MACHINEGUNS,
	TYPE_SMG,
	TYPE_AIRBOATGUN,
	TYPE_SHOTGUN,
	TYPE_ANNABELLE,
	TYPE_BEAM,
	TYPE_RPG,
	TYPE_GRENADE,
	TYPE_LAST
} WeaponType;
#endif