//====== Copyright © 2008-2021 ================================================
//
// Purpose: Overcharged Serverside events declaration
//
//=============================================================================
// Hammer editor event example : logic_achievement -> ACHIEVEMENT_EVENT_HL2_PUT_CANINTRASH -> FireEvent output

#include "cbase.h"

#if GAME_DLL

#define DEF_OVER_ACH 1
#if DEF_OVER_ACH

#include "achievementmgr.h"
#include "baseachievement.h"

CAchievementMgr g_AchievementMgrOverchar;

DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_ATAKMOZNO, "ACHIEVEMENT_OVR_ATAKMOZNO", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_FREE_MAN, "ACHIEVEMENT_OVR_FREE_MAN", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_BUSTED, "ACHIEVEMENT_OVR_BUSTED", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_DANCINGSCANNER, "ACHIEVEMENT_OVR_DANCINGSCANNER", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_THE_AR3, "ACHIEVEMENT_OVR_THE_AR3	", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_MEETXENIANS, "ACHIEVEMENT_OVR_MEETXENIANS	", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_CREEDOF, "ACHIEVEMENT_OVR_CREEDOF	", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_FINDSKULLS, "ACHIEVEMENT_OVR_FINDSKULLS", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_HEAVYWEAPONS, "ACHIEVEMENT_OVR_HEAVYWEAPONS", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_CASTFROMPAST, "ACHIEVEMENT_OVR_CASTFROMPAST", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_CRYSTALBMEAST, "ACHIEVEMENT_OVR_CRYSTALBMEAST", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_MEMORIESOFBEAM, "ACHIEVEMENT_OVR_MEMORIESOFBEAM", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_CHANGEFIREMODES, "ACHIEVEMENT_OVR_CHANGEFIREMODES", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_OLDHEVFIND, "ACHIEVEMENT_OVR_OLDHEVFIND", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_WORKDIGGIN, "ACHIEVEMENT_OVR_WORKDIGGIN", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_LIKEFATHER, "ACHIEVEMENT_OVR_LIKEFATHER", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_SPORERULES, "ACHIEVEMENT_OVR_SPORERULES", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_TESTDRIVE, "ACHIEVEMENT_OVR_TESTDRIVE", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_ELISPRIDE, "ACHIEVEMENT_OVR_ELISPRIDE", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_DONTLETIT, "ACHIEVEMENT_OVR_DONTLETIT", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_THATSSOCUTE, "ACHIEVEMENT_OVR_THATSSOCUTE", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_PORTABILITY, "ACHIEVEMENT_OVR_PORTABILITY", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_WALKINGONCOAST, "ACHIEVEMENT_OVR_WALKINGONCOAST", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_COMBINEDREVENGE, "ACHIEVEMENT_OVR_COMBINEDREVENGE", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_BATTLEOFTECH, "ACHIEVEMENT_OVR_BATTLEOFTECH", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_MONTANAMANSION, "ACHIEVEMENT_OVR_MONTANAMANSION", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_FIGHTINDARK, "ACHIEVEMENT_OVR_FIGHTINDARK", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_NOTIME, "ACHIEVEMENT_OVR_NOTIME", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_VISINVIS, "ACHIEVEMENT_OVR_VISINVIS", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_VICEVERSA, "ACHIEVEMENT_OVR_VICEVERSA", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_GNOMED, "ACHIEVEMENT_OVR_GNOMED", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_DOUBLEREACT, "ACHIEVEMENT_OVR_DOUBLEREACT", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_NOALCO, "ACHIEVEMENT_OVR_NOALCO", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_KNOWYOURENEMY, "ACHIEVEMENT_OVR_KNOWYOURENEMY", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_OVR_LASTMANANDVORT, "ACHIEVEMENT_OVR_LASTMANANDVORT", 5);


//DECLARE_MAP_EVENT_ACHIEVEMENT_HIDDEN( ACHIEVEMENT_AA_FIND_CUBE, "AA_FIND_CUBE", 5 );

#endif	// ach enable disable

#endif // GAME_DLL