//====== Copyright © 2008-2021 ================================================
//
// Purpose: AA Serverside events declaration
//
//=============================================================================
// Hammer editor event example : logic_achievement -> ACHIEVEMENT_EVENT_HL2_PUT_CANINTRASH -> FireEvent output

#include "cbase.h"

#if GAME_DLL

#define DEF_AA_ACH 0
#if DEF_AA_ACH

#include "achievementmgr.h"
#include "baseachievement.h"

CAchievementMgr g_AchievementMgrArctic;

DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_AA_WELCOME_TO_ARCTIC, "AA_WELCOME_TO_ARCTIC", 5 );
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_AA_SURVIVE_THE_CHASE, "AA_SURVIVE_THE_CHASE", 5 );
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_AA_DISCOVER_THE_SHIP, "AA_DISCOVER_THE_SHIP", 5 );
DECLARE_MAP_EVENT_ACHIEVEMENT( ACHIEVEMENT_AA_KILL_5_HEAVY_SOLDIERS, "AA_KILL_5_HEAVY_SOLDIERS", 5 );
DECLARE_MAP_EVENT_ACHIEVEMENT_HIDDEN( ACHIEVEMENT_AA_FIND_CUBE, "AA_FIND_CUBE", 5 );
DECLARE_MAP_EVENT_ACHIEVEMENT_HIDDEN( ACHIEVEMENT_AA_FIND_CHUMTOAD, "AA_FIND_CHUMTOAD", 5 );
DECLARE_MAP_EVENT_ACHIEVEMENT_HIDDEN( ACHIEVEMENT_AA_FIND_HAT, "AA_FIND_HAT", 5 );
DECLARE_MAP_EVENT_ACHIEVEMENT_HIDDEN( ACHIEVEMENT_AA_WAIT_FOR_PORTAL, "AA_WAIT_FOR_PORTAL", 5 );

DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_SHEP_FREE_SLAVES, "SHEP_FREE_SLAVES", 5);	// update 1
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_SHEP_PUZZLE, "SHEP_PUZZLE", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_SHEP_STILLALIVE, "SHEP_STILLALIVE", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_AA_SOFT_DRINKS, "AA_SOFT_DRINKS", 5);
DECLARE_MAP_EVENT_ACHIEVEMENT_HIDDEN(ACHIEVEMENT_AA_FIND_POTATOS, "AA_FIND_POTATOS", 5);

DECLARE_MAP_EVENT_ACHIEVEMENT(ACHIEVEMENT_AA2_SPECULATION, "AA2_SPECULATION", 5);	// update 2

#endif	// ach enable disable


#endif // GAME_DLL